# https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
${custom.mise_elixir}\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$fill\
$time\
$line_break\
$character"""

# The built in Elixir module is slow, hence the custom module.
# https://github.com/starship/starship/issues/3867

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[directory]
style = "blue"
truncation_length = 20
truncate_to_repo = true
truncation_symbol = "…"
#fish_style_pwd_dir_length = 1
repo_root_style = "underline italic blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[✗](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$symbol$branch]($style)"
style = "color_yellow"

[git_status]
disabled = false
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[custom.mise_elixir]
command = 'mise current elixir'
detect_files = ["mix.exs"]
# symbol = '💧'
# symbol = '🔮'
style = "bold purple"

[fill]
symbol = ' '

[time]
disabled = false
time_format = "%R"
format = '[[  $time ](fg:color_fg0)]($style)'

[cmd_duration]
format = "took [$duration]($style) "
style = "yellow"

